### ISSUE TITLE
Correlation factors?

### ISSUE THREAD

**Issue by RicardoJFP** [SJTU-Quant/MASTER#4]
Congrats for this work, it's certainly innovative.
I have question regarding the mine function on the momentary and cross-time stock correlation - which data are you mainly considering (variables used)? Are you mainly looking at stock / portfolio price correlation or are considering finding stock price correlation with other market factors?

**Comment by LITONG99** [comment]
Thank you for your attention to this work.
We consider Alpha158 factors, which is a set of handcrafted features derived from basic variables such as OHLCV data. Alpha158 contains indicative information about the future stock price (a clue is that simple regression models on Alpha158 achieve fair performance sometimes). MASTER mines the correlation between stock prices. Indicative features instead of a single price value are used for robustness.

The manuscripts, data, and code of MASTER are all published, please refer to them for more details.
