### ISSUE TITLE
Can you provide the detailed code about how Market information is calculated?

### ISSUE THREAD

**Issue by XFeiF** [SJTU-Quant/MASTER#7]
I just found the value of `feature.1` can not be inferred from the column `feature`. 
  | feature | feature.1
-- | -- | --
  | Mask($close/Ref($close,1)-1,'SH000300') | Mask(Mean($close/Ref($close,1)-1,5),'SH000300')
datetime |   |  
2008/1/2 | 0.74735785 | 1.0109634
2008/1/3 | 0.57677513 | 1.1709653
2008/1/4 | 0.9783356 | 1.2388867
2008/1/7 | 1.1510324 | 1.0415094
2008/1/8 | -0.4920946 | 1.0515707
2008/1/9 | 1.3472286 | 1.2670099

For example, at  `2008/1/8`  , the `feature.1` 's value is 1.0515707.
While according to the expression `Mask(Mean($close/Ref($close,1)-1,5),'SH000300')`, I think it can be simply calculated by `(0.74735785 + 0.57677513 + 0.9783356 + 1.1510324 -0.4920946 ) / 5`, and the result is 0.592281276.

Do I misunderstand the expression of `feature.1`? Can anyone explain this?
Besides, can you provide the detailed code about how Market information is calculated?

Many thanks!

**Comment by LITONG99** [comment]
Both the market information and the 158 factors are considered as features, which means they undergo the same preprocessing. Sorry that I missed pointing this out earlier, and please refer to `Readme/Dataset/Preprocessing` for a description. 

Specifically, the range of market information is `[-3,3]`, which is due to the `RobustZScoreNorm` in Qlib. It is a common practice in Qlib and please refer to the Qlib documents for explanation. You may also find [my answer to this closed issue](https://github.com/SJTU-Quant/MASTER/issues/3#issuecomment-2015411800) helpful.

Based on the Qlib, a version of data preprocessing code is already available, which includes detailed code to calculate market information from raw data. Please refer to `Readme/[New]A-Qlib-implementation`.
