### ISSUE TITLE
Inconsistent master dataset handling

### ISSUE THREAD

**Issue by caozhiy** [SJTU-Quant/MASTER#8]
Thank you for your fancy job!

Recently when I wanted to use Qlib to get a dataset in Master format for the latest time, I found that the Label handling method integrated in Qlib was inconsistent with the method provided by the author in Issue. The `CSRankNorm` is used for Label in Qlib, but the author provides `CSZScoreNorm` to process Label.

May I ask which method is correct?

Best wishes!

Handler provided by author
![image](https://github.com/SJTU-Quant/MASTER/assets/85427458/8632c592-adce-441d-b6ae-067cd8691e86)

Qlib Handler
![image](https://github.com/SJTU-Quant/MASTER/assets/85427458/6c7489e5-31ef-4036-871b-afd071376134)

**Comment by LITONG99** [comment]
Thanks for pointing out the inconsistency to us. 

To align with our experiments, please use `CSZScoreNorm` as we did, which is also specified in our paper. You can simply alter the `.yaml` configuration.

If there are other conflicts, please refer to the published paper and the content in this repository for clarification. 

For discussion, if you use the `CSRankNorm`, the label is the normalized rank instead of the normalized return ratio. It is reasonable to use either of the two settings to train the MASTER model and the reported metrics will be ‘correct’ in the corresponding setting.
